settings:
  #This can be named anything, it's not important
  world:
    #What world do we want to spawn them in
    spawnWorld: "KitPVP"
    #If they die in any of these worlds, they will respawn in spawnWorld
    deathWorlds:
      - "KitPVP"
      - "TestWorld"
  anotherWorld:
    spawnWorld: "Nether"
    deathWorlds:
      - "The End"
      - "Factions"